chore: added function calls proposal
cdklabs/decdk pull request #147
Opened 2022-07-18 12:15 UTC by otaviomacedo

Proposals for function call syntax in deCDK. We'd love to get feedback from the community on what their preferred syntax is, things we have missed, new ideas etc.

2022-08-23 13:31 UTC, mrgrain requested changes

2022-08-23 13:31 UTC, mrgrain commented on docs/function-calls-syntax.md
> +    Type: aws-cdk-lib.aws_appsync..LambdaDataSource
```suggestion
    Type: aws-cdk-lib.aws_appsync.LambdaDataSource
```

2022-08-23 13:34 UTC, mrgrain submitted a review, later dismissed
LGTM. Added `do-not-merge` label in case you'd like @jlhood to have another look.

2022-09-08 12:28 UTC, mrgrain commented
```yaml
Resources:
  MyAccessPoint:
    Type: AWSCDK::Call
    Target:
      Ref: MyFileSystem # this can also be 
        Function: 'AddAccessPoint'
        Arguments:
            - 'AccessPoint'
```

```yaml
Resources:
  MyBucket:
    Type: AWSCDK::Call
    Target: aws-cdk-lib.aws_s3.Bucket
    Target:
      Fqn: aws-cdk-lib.aws_s3.Bucket
    Function: 'fromBucketName'
    Arguments:
      - 'AccessPoint'

  MyBucketDeployment:
    Type: aws-cdk-lib.aws_s3_deployment.BucketDeployment
    Properties:
      bucket: 
        aws-cdk-lib.aws_s3.Bucket.fromBucketName: my-bucket
```

2022-09-08 13:15 UTC, rix0rrr commented
Here are some more possibilities we talked about:

```yaml


  SomeComplexValue:
    Value: { 'Cdk::Call': { aws-cdk-lib.Duration.seconds: 5 } }
    ObviousContext: { aws-cdk-lib.Duration.seconds: 5 }  # <-- common scenario, therefore lightweight syntax


Resources:
  BlaBucket:
    Type: aws-cdk-lib.aws_s3.Bucket
    Properties:
      SomeThingTypedAsAny: { 'Cdk::Call': { aws-cdk-lib.aws_s3.Bucket.grantRead: [{ Ref: MyBucket }, 'files/*'] } } # <-- disallow!
      SomeThingTypedAsAny: { aws-cdk-lib.aws_s3.Bucket.grantRead: [{ Ref: MyBucket }, 'files/*'] }  

  # Member function 1
  BucketPermissions:
    Type: aws-cdk-lib.aws_iam.Grant
    On: { Ref: BlaBucket }
    Call: { grantRead: 'files/*' }
      
  # Member function 2
  BucketPermissions:
    Type: aws-cdk-lib.aws_iam.Grant
    Call: { aws-cdk-lib.aws_s3.Bucket.grantRead: [{ Ref: MyBucket }, 'files/*'] } # <-- Python/C++ like unbound member functions
    Call: { aws-cdk-lib.aws_s3.Bucket.grantRead: ['MyBucket', 'files/*'] }

  # Member function 3
  BucketPermissions:
    Type: aws-cdk-lib.aws_iam.Grant
    Call: { MyBucket.grantRead: 'files/*' }

  # Static function 1
  BucketPermissions:
    Type: aws-cdk-lib.aws_iam.Grant
    On: aws-cdk-lib.aws_s3.Bucket
    Call: { fromBucketName: 'files/*' }

  # Static function 2
  BucketPermissions:
    # Type: aws-cdk-lib.aws_s3.Bucket (optional?)
    Call: { aws-cdk-lib.aws_s3.Bucket.fromBucketName: { Ref: MyL1Bucket } }

```

2022-09-08 13:27 UTC, rix0rrr commented
About scope and ID:

```
  BucketPermissions:
    # Type: aws-cdk-lib.aws_s3.Bucket (optional?)
    Call: { aws-cdk-lib.aws_s3.Bucket.fromBucketName: { Ref: MyL1Bucket } }
    Call: { aws-cdk-lib.aws_s3.Bucket.fromBucketName: { 'Cdk::Args': [{ Ref: 'CDK::Scope' }, 'BucketPermissions', { Ref: MyL1Bucket }] } }

```

2022-09-29 10:09 UTC, closed without merging

2022-10-18 13:56 UTC, mrgrain commented
```yaml
 # Member function 4
  BucketPermissions:
    Type: aws-cdk-lib.aws_iam.Grant
    Call:
      - MyBucket 
      - grantRead: 'files/*' 
```